### ISSUE TITLE
您好，chinese/2.merge_sgns_bigram_char300.txt是否可以共享，谢谢

### ISSUE THREAD

**Issue by Williamlizl** [SunnyMarkLiu/lic2019-dureader2.0-rank2#4]

**Comment by SunnyMarkLiu** [comment]
您好，词向量我们是从这个 repo 下载的：https://github.com/Embedding/Chinese-Word-Vectors

**Comment by Williamlizl** [comment]
Hi,


好的，谢谢你


Best Regards




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Qing Liu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月6日(星期五) 中午1:40
收件人:&nbsp;"SunnyMarkLiu/lic2019-dureader2.0-rank2"<lic2019-dureader2.0-rank2@noreply.github.com&gt;;
抄送:&nbsp;"李博超"<917988967@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [SunnyMarkLiu/lic2019-dureader2.0-rank2] 您好，chinese/2.merge_sgns_bigram_char300.txt是否可以共享，谢谢 (#4)




您好，词向量我们是从这个 repo 下载的：https://github.com/Embedding/Chinese-Word-Vectors

**Comment by Williamlizl** [comment]
Hi,





split_search_00这种文件是自己分开的还是怎么生成的呢，有点没想明白，期待您的解答。


Best Regards




------------------ 原始邮件 ------------------
发件人:&nbsp;"Qing Liu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月6日(星期五) 中午1:40
收件人:&nbsp;"SunnyMarkLiu/lic2019-dureader2.0-rank2"<lic2019-dureader2.0-rank2@noreply.github.com&gt;;
抄送:&nbsp;"李博超"<917988967@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [SunnyMarkLiu/lic2019-dureader2.0-rank2] 您好，chinese/2.merge_sgns_bigram_char300.txt是否可以共享，谢谢 (#4)




您好，词向量我们是从这个 repo 下载的：https://github.com/Embedding/Chinese-Word-Vectors

**Comment by SunnyMarkLiu** [comment]
google 下 linux 的 split 命令，分成多个文件块之后多进程处理的
